% This file is to be included by https://gitlab.mpcdf.mpg.de/elpa/elpa-doc/-/raw/main/src/elpa_doc.tex

% TODO: add automatic parsing of elpa_api.F90, elpa_api_math_template.F90, and others (check with grep).
% It should create this file automatically and issue a warning is some of the man pages are missing.

\includePdfSubsec{elpa2\_print\_kernels}{\getManPDFfolder/elpa2_print_kernels.pdf}
\includePdfSubsec{elpa\_allocate}{\getManPDFfolder/elpa_allocate.pdf}
\includePdfSubsec{elpa\_autotune\_deallocate}{\getManPDFfolder/elpa_autotune_deallocate.pdf}
\includePdfSubsec{elpa\_autotune\_load\_state}{\getManPDFfolder/elpa_autotune_load_state.pdf}
\includePdfSubsec{elpa\_autotune\_print\_state}{\getManPDFfolder/elpa_autotune_print_state.pdf}
\includePdfSubsec{elpa\_autotune\_save\_state}{\getManPDFfolder/elpa_autotune_save_state.pdf}
\includePdfSubsec{elpa\_autotune\_set\_best}{\getManPDFfolder/elpa_autotune_set_best.pdf}
\includePdfSubsec{elpa\_autotune\_setup}{\getManPDFfolder/elpa_autotune_setup.pdf}
\includePdfSubsec{elpa\_autotune\_step}{\getManPDFfolder/elpa_autotune_step.pdf}
\includePdfSubsec{elpa\_cholesky}{\getManPDFfolder/elpa_cholesky.pdf}
\includePdfSubsec{elpa\_deallocate}{\getManPDFfolder/elpa_deallocate.pdf}
\includePdfSubsec{elpa\_eigenvalues\_double\_complex}{\getManPDFfolder/elpa_eigenvalues_double_complex.pdf}
\includePdfSubsec{elpa\_eigenvalues\_double}{\getManPDFfolder/elpa_eigenvalues_double.pdf}
\includePdfSubsec{elpa\_eigenvalues\_float\_complex}{\getManPDFfolder/elpa_eigenvalues_float_complex.pdf}
\includePdfSubsec{elpa\_eigenvalues\_float}{\getManPDFfolder/elpa_eigenvalues_float.pdf}
\includePdfSubsec{elpa\_eigenvalues}{\getManPDFfolder/elpa_eigenvalues.pdf}
\includePdfSubsec{elpa\_eigenvectors\_double\_complex}{\getManPDFfolder/elpa_eigenvectors_double_complex.pdf}
\includePdfSubsec{elpa\_eigenvectors\_double}{\getManPDFfolder/elpa_eigenvectors_double.pdf}
\includePdfSubsec{elpa\_eigenvectors\_float\_complex}{\getManPDFfolder/elpa_eigenvectors_float_complex.pdf}
\includePdfSubsec{elpa\_eigenvectors\_float}{\getManPDFfolder/elpa_eigenvectors_float.pdf}
\includePdfSubsec{elpa\_eigenvectors}{\getManPDFfolder/elpa_eigenvectors.pdf}
\includePdfSubsec{elpa\_generalized\_eigenvalues}{\getManPDFfolder/elpa_generalized_eigenvalues.pdf}
\includePdfSubsec{elpa\_generalized\_eigenvectors}{\getManPDFfolder/elpa_generalized_eigenvectors.pdf}
\includePdfSubsec{elpa\_get\_communicators}{\getManPDFfolder/elpa_get_communicators.pdf}
\includePdfSubsec{elpa\_hermitian\_multiply}{\getManPDFfolder/elpa_hermitian_multiply.pdf}
\includePdfSubsec{elpa\_init}{\getManPDFfolder/elpa_init.pdf}
\includePdfSubsec{elpa\_invert\_triangular}{\getManPDFfolder/elpa_invert_triangular.pdf}
\includePdfSubsec{elpa\_load\_settings}{\getManPDFfolder/elpa_load_settings.pdf}
\includePdfSubsec{elpa\_print\_settings}{\getManPDFfolder/elpa_print_settings.pdf}
\includePdfSubsec{elpa\_set}{\getManPDFfolder/elpa_set.pdf}
\includePdfSubsec{elpa\_setup}{\getManPDFfolder/elpa_setup.pdf}
\includePdfSubsec{elpa\_skew\_eigenvalues}{\getManPDFfolder/elpa_skew_eigenvalues.pdf}
\includePdfSubsec{elpa\_skew\_eigenvectors}{\getManPDFfolder/elpa_skew_eigenvectors.pdf}
\includePdfSubsec{elpa\_solve\_tridiagonal}{\getManPDFfolder/elpa_solve_tridiagonal.pdf}
\includePdfSubsec{elpa\_store\_settings}{\getManPDFfolder/elpa_store_settings.pdf}
\includePdfSubsec{elpa\_uninit}{\getManPDFfolder/elpa_uninit.pdf} 
