.TH "elpa_autotune_step" 3 "Wed Aug 9 2023" "ELPA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elpa_autotune_step \- does one ELPA autotuning step
.br
Before the autotuning step can be done, an instance of the ELPA autotune object has to be created, see\fB elpa_autotune_setup\fP(3)

.SH SYNOPSIS
.br
.SS FORTRAN INTERFACE
use elpa
.br
class(elpa_t), pointer :: elpa
.br
class(elpa_autotune_t), pointer :: tune_state
.br

unfinished = elpa%\fBautotune_step\fP (tune_state)
.sp
With the definitions of the input and output variables:
.TP
type(elpa_autotune_t) :: \fB tune_state\fP  
The ELPA autotuning object, created with\fB elpa_autotune_setup\fP(3)
.TP
logical               :: \fB unfinished\fP 
Logical, specifying whether autotuning has finished (.false.) or not (.true.)
.br

.SS C INTERFACE
#include <elpa/elpa.h>
.br
elpa_t handle;
.br
elpa_autotune_t autotune_handle;

.br
\fBint\fP unfinished =\fB elpa_autotune_step\fP (\fBelpa_t\fP handle,\fB elpa_autotune_t\fP autotune_handle);
.sp
With the definitions of the input and output variables:
.TP
elpa_t \fB handle\fP;                   
The handle of an ELPA object, obtained before with\fB elpa_allocate\fP(3)
.TP
elpa_autotune_t\fB autotune_handle\fP;  
The handle of the autotuning object, created with\fB elpa_autotune_setup\fP(3)
.TP
int \fB unfinished\fP;                  
Integer, specifying whether autotuning has finished (0) or not (1)

.SH DESCRIPTION
Performs an ELPA autotuning step.\fI Prior\fP to calling  the autotune_step, an ELPA autotune object must have been created.
See\fB elpa_autotune_setup\fP(3)

.SH SEE ALSO
\fBelpa_autotune_setup\fP(3)\fB elpa_autotune_set_best\fP(3)\fB elpa_autotune_deallocate\fp(3)

