.TH "elpa_uninit" 3 "Wed Aug 9 2023" "ELPA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elpa_uninit \- uninitializes the ELPA library
.br

.SH SYNOPSIS
.br
.SS FORTRAN INTERFACE
use elpa
.br
class(elpa_t), pointer :: elpa
.br

call\fB elpa_uninit\fP (error)
.sp
With the definitions of the input and output variables:
.TP
integer, optional :: error 
The error code
.br

.br
.SS C INTERFACE
#include <elpa/elpa.h>
.br
elpa_t handle;

.br
\fBvoid elpa_uninit\fP (int *error);
.sp
With the definitions of the input and output variables:
.TP
int \fB error*\fP;
The error code
.br

.SH DESCRIPTION
Uninitializes the ELPA library after usage. The function\fB elpa_init\fP(3) must have been called\fI BEFORE\fP elpa_uninit can be called.

.SH SEE ALSO
\fBelpa2_print_kernels\fP(1)\fB elpa_init\fP(3)\fB elpa_allocate\fP(3)\fB elpa_set\fP(3)\fB elpa_strerr\fP(3)\fB elpa_eigenvalues\fP(3)\fB elpa_eigenvectors\fP(3)\fB elpa_cholesky\fP(3)\fB elpa_invert_triangular\fP(3)\fB elpa_solve_tridiagonal\fP(3)\fB elpa_hermitian_multiply\fP(3)\fB elpa_setup\fP(3)\fB elpa_deallocate\fP(3)
