.TH "elpa_autotune_load_state" 3 "Fri Feb 9 2024" "ELPA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elpa_autotune_load_state \- loads a state of an ELPA autotuning object
.br

.SH SYNOPSIS
.br
.SS FORTRAN INTERFACE
use elpa
.br
class(elpa_t), pointer :: elpa
class(elpa_autotune_t), pointer :: autotune
.br

call elpa%\fBautotune_load_state\fP (autotune, filename, error)
.sp
With the definitions of the input and output variables:
.TP
class(elpa_t)          :: \fB elpa\fP       
An instance of the ELPA object
.TP
class(elpa_autotune_t) :: \fB autotune\fP   
An instance of the ELPA autotune object
.TP
character(*)           :: \fB filename\fP   
The filename to be used for loading the settings
.TP
integer, optional      :: \fB error\fP      
An error return code
.br

.SS C INTERFACE
#include <elpa/elpa.h>
.br
elpa_t handle;
.br
elpa_autotune_t autotune_handle;

void\fB elpa_autotune_load_state\fP(\fBelpa_t\fP handle,\fB elpa_autotune_t\fP autotune_handle,\fB const char\fP *filename,\fB int\fP *error);
.sp
With the definitions of the input and output variables:
.TP
elpa_t \fB handle\fP;                
The handle to the ELPA object
.TP
elpa_autotune_t \fB handle\fP;       
The handle to the ELPA autotune object
.TP
const char \fB *filename\fP;         
The filename to load the settings
.TP
int \fB *error\fP;                   
The error return code

.SH DESCRIPTION
Loads a previously stored state of an autotune object. With the loaded, state the autotuning could be resumed.

.SH SEE ALSO
\fBelpa_autotune_save_state\fP(3)
