.TH "elpa_load_settings" 3 "Wed Aug 9 2023" "ELPA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elpa_load_settings \- loads the setting of an elpa object
.br

.SH SYNOPSIS
.br
.SS FORTRAN INTERFACE
use elpa
.br
class(elpa_t), pointer :: elpa
.br

call elpa%\fBload_settings\fP (filename, error)
.sp
With the definitions of the input and output variables:
.TP
class(elpa_t)       :: \fB elpa\fP
An instance of the ELPA object
.TP
character(*)        :: \fB filename\fP  
The file from where to load the settings
.TP
integer, optional   :: \fB error\fP     
An error return code
.br

.SS C INTERFACE
#include <elpa/elpa.h>
.br
elpa_t handle;

.br
void\fB elpa_load_settings\fP(\fBelpa_t\fP handle,\fB const char\fP *filename,\fB int\fP *error);
.sp
With the definitions of the input and output variables:
.TP
elpa_t \fB handle\fP;        
The handle to the ELPA object
.TP
const char \fB *filename\fP; 
The filename to load the settings
.TP
int \fB *error\fP;           
The error return code

.SH DESCRIPTION
Loads all the settings of an previously stored ELPA object from a file specified via the \fB filename\fP parameter.

.SH SEE ALSO
\fBelpa_store_setting\fP(3)
