.TH "elpa_store_settings" 3 "Fri Feb 9 2024" "ELPA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elpa_store_settings \- stores the setting of an elpa object
.br

.SH SYNOPSIS
.br
.SS FORTRAN INTERFACE
use elpa
.br
class(elpa_t), pointer :: elpa
.br

call elpa%\fBstore_settings\fP (filename, error)
.sp
With the definitions of the input and output variables:
.TP
class(elpa_t)      :: \fB elpa\fP      
An instance of the ELPA object
.TP
character(*)       :: \fB filename\fP  
The filename to be used for storing the settings
.TP
integer, optional  :: \fB error\fP    
An error return code
.br

.SS C INTERFACE
#include <elpa/elpa.h>
.br
elpa_t handle;

.br
void\fB elpa_store_settings\fP(\fBelpa_t\fP handle,\fB const char\fP *filename,\fB int\fP *error);
.sp
With the definitions of the input and output variables:
.TP
elpa_t \fB handle\fP;          
The handle to the ELPA object
.TP
const char \fB *filename\fP;   
The filename to store the settings
.TP
int \fB *error\fP;             
The error return code

.SH DESCRIPTION
Stores all the settings of an ELPA object in a human readable form to a file specified via the\fB filename\fP parameter. The settings can later be restored with the
\fBelpa_load_settings\fP(3) method.

.SH SEE ALSO
\fBelpa_load_setting\fP(3)
