.TH "elpa_autotune_set_best" 3 "Wed Aug 9 2023" "ELPA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elpa_autotune_set_best \- sets the tunable parameters to the up-to-now best solution
.br
Before the autotuning options can be set, an autotuning step has to be done\fB elpa_autotune_step\fP(3)

.SH SYNOPSIS
.br
.SS FORTRAN INTERFACE
use elpa
.br
class(elpa_t), pointer :: elpa
.br
class(elpa_autotune_t), pointer :: tune_state
.br

call elpa%\fBautotune_set_best\fP (tune_state)
.sp
With the definitions of the input and output variables:
.TP
type(elpa_autotune_t) :: \fB tune_state\fP  
The ELPA autotuning object, created with\fB elpa_autotune_setup\fP(3)
.br

.SS C INTERFACE
#include <elpa/elpa.h>
.br
elpa_t handle;
.br
elpa_autotune_t autotune_handle;

.br
void\fB elpa_autotune_set_best\fP (\fBelpa_t\fP handle,\fB elpa_autotune_t\fP autotune_handle);
.sp
With the definitions of the input and output variables:
.TP
elpa_t \fB handle\fP;  
The handle of an ELPA object, obtained before with\fB elpa_allocate\fP(3)
.TP
elpa_autotune_t\fB autotune_handle\fP;  
The handle of an ELPA object, obtained before with\fB elpa_autotune_setup\fP(3)

.SH DESCRIPTION
Sets the up-to-now best options for ELPA tunable parameters.\fI Prior\fP to calling the elpa_autotune_set_best method,
an ELPA autotuning step must have been performed. See\fB elpa_autotune_set_best\fP(3)

.SH SEE ALSO
\fBelpa_autotune_step\fP(3)\fB elpa_autotune_setup\fP(3)\fB elpa_autotune_deallocate\fp(3)

