.TH "elpa_autotune_deallocate" 3 "Wed Mar 20 2024" "ELPA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elpa_autotune_deallocate \- deallocates an ELPA autotuning instance
.br

.SH SYNOPSIS
.br
.SS FORTRAN INTERFACE
use elpa
.br
class(elpa_t), pointer :: elpa
class(elpa_autotune_t), pointer :: tune_state
.br

call elpa%\fBautotune_deallocate\fP (tune_state, error)
.sp
With the definitions of the input and output variables:

.TP
type(elpa_autotune_t) :: \fB tune_state\fP  
The ELPA autotuning object, created with\fB elpa_autotune_setup\fP(3)
.TP
integer, optional     :: \fB error\fP
The returned error code

.SS C INTERFACE
#include <elpa/elpa.h>
.br
elpa_autotune_t autotune_handle;

void\fB elpa_autotune_deallocate\fP (\fBelpa_autotune_t\fP autotune_handle,\fB int\fP *error);
.sp
With the definitions of the input and output variables:

.TP
elpa_autotune_t\fB autotune_handle\fP;
The handle of an ELPA object, obtained before with\fB elpa_autotune_setup\fP(3)
.TP
int \fB *error\fP;
The returned error code

.SH DESCRIPTION
Deallocates an ELPA autotuning instance.\fI Prior\fP to calling the elpa_autotune_deallocate method,
an ELPA autotuning object must have been created. See\fB elpa_autotune_setup\fP(3)

.SH SEE ALSO
\fBelpa_autotune_step\fP(3)\fB elpa_autotune_setup\fP(3)\fB elpa_autotune_deallocate\fp(3)

