.TH "elpa_cholesky_real_single" 3 "Wed Jun 29 2016" "ELPA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elpa_cholesky_real_single \- Cholesky factorization of a real symmetric matrix
.br

.SH SYNOPSIS
.br
.SS FORTRAN INTERFACE
use elpa1
.br
.br
.RI  "success = \fBelpa_cholesky_real_single\fP (na, a(lda,matrixCols), lda, nblk, matrixCols, mpi_comm_rows, mpi_comm_cols, wantDebug)"
.br
.RI " "
.br
.RI "With the definintions of the input and output variables:"

.br
.RI "integer, intent(in)    \fBna\fP:            global dimension of quadratic matrix \fBa\fP to solve"
.br
.RI "real*4,  intent(inout) \fBa\fP:             locally distributed part of the matrix \fBa\fP. The local dimensions are \fBlda\fP x \fBmatrixCols\fP"
.br
.RI "integer, intent(in)    \fBlda\fP:           leading dimension of locally distributed matrix \fBa\fP"
.br
.RI "integer, intent(in)    \fBnblk\fP:          blocksize of cyclic distribution, must be the same in both directions"
.br
.RI "integer, intent(in)    \fBmatrixCols\fP:    number of columns of locally distributed matrices \fBa\fP and \fBq\fP"
.br
.RI "integer, intent(in)    \fBmpi_comm_rows\fP: communicator for communication in rows. Constructed with \fBget_elpa_communicators\fP(3)"
.br
.RI "integer, intent(in)    \fBmpi_comm_cols\fP: communicator for communication in colums. Constructed with \fBget_elpa_communicators\fP(3)"
.br
.RI "logical, intent(in)    \fBwantDebug\fP:     if .true. , print more debug information in case of an error"

.RI "logical                \fBsuccess\fP:       return value indicating success or failure"
.br
.SS C INTERFACE
#include "elpa.h"

.br
.RI "\fBint\fP success = \fBelpa_cholesky_real_single\fP (\fBint\fP na, \fB float *\fPa, \fBint\fP lda, \fBint\fP nblk, \fBint\fP matrixCols, \fBint\fP mpi_comm_rows, \fBint\fP mpi_comm_cols, \fBint\fP wantDebug );"
.br
.RI " "
.br
.RI "With the definintions of the input and output variables:"

.br
.RI "int     \fBna\fP:            global dimension of quadratic matrix \fBa\fP to solve"
.br
.RI "floar  *\fBa\fP:             pointer to locally distributed part of the matrix \fBa\fP. The local dimensions are \fBlda\fP x \fBmatrixCols\fP"
.br
.RI "int     \fBlda\fP:           leading dimension of locally distributed matrix \fBa\fP"
.br
.RI "int     \fBnblk\fP:          blocksize of block cyclic distributin, must be the same in both directions"
.br
.RI "int     \fBmatrixCols\fP:    number of columns of locally distributed matrices \fBa\fP and \fBq\fP"
.br
.RI "int     \fBmpi_comm_rows\fP: communicator for communication in rows. Constructed with \fBget_elpa_communicators\fP(3)"
.br
.RI "int     \fBmpi_comm_cols\fP: communicator for communication in colums. Constructed with \fBget_elpa_communicators\fP(3)"
.br
.RI "int     \fBwantDebug\fP:     if 1, print more debug information in case of an error"
.br

.RI "int     \fBsuccess\fP:       return value indicating success (1) or failure (0)

.SH DESCRIPTION
Does a Cholesky factorization of a real, symmetric matrix. The ELPA communicators \fBmpi_comm_rows\fP and \fBmpi_comm_cols\fP are obtained with the \fBget_elpa_communicators\fP(3) function. The distributed quadratic marix \fBa\fP has global dimensions \fBna\fP x \fBna\fP, and a local size \fBlda\fP x \fBmatrixCols\fP.
.br
.SH "SEE ALSO"
\fBget_elpa_communicators\fP(3) \fBelpa_cholesky_real\fP(3) \fBelpa_cholesky_real_double\fP(3)
