.TH "elpa_print_settings" 3 "Fri Feb 9 2024" "ELPA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elpa_print_settings \- prints the setting of an elpa object
.br

.SH SYNOPSIS
.br
.SS FORTRAN INTERFACE
use elpa
.br
class(elpa_t), pointer :: elpa
.br

call elpa%\fBprint_settings\fP (error)
.sp
With the definitions of the input and output variables:
.TP
class(elpa_t)       \fB elpa\fP    
An instance of the ELPA object
.TP
integer, optional   \fB error\fP   
An error return code
.br

.SS C INTERFACE
#include <elpa/elpa.h>
.br
elpa_t handle;

.br
void\fB elpa_print_settings\fP(\fBelpa_t\fP handle,\fB int\fP *error);
.sp
With the definitions of the input and output variables:
.TP
elpa_t \fB handle\fP;    
The handle to the ELPA object
.TP
int \fB *error\fP;       
The error return code

.SH DESCRIPTION
Prints all the settings of an ELPA object. The settings can be stored, or loaded with\fB elpa_store_settings\fP.3 or\fB elpa_load_settings\fP.3

.SH SEE ALSO
\fBelpa_store_setting\fP(3)\fB elpa_load_settings\fP.(3)
