.TH "elpa_allocate" 3 "Wed Aug 9 2023" "ELPA" \" -*- nroff -*-
.ft C
.ad l
.nh
.SH NAME
.RI "elpa_allocate \- allocates an instance of the ELPA library"
.br

.SH SYNOPSIS
.br
.SS FORTRAN INTERFACE
use elpa
.br
class(elpa_t), pointer :: elpa
.br

elpa =>\fB elpa_allocate\fP (error)
.sp
With the definitions of the input and output variables:

.TP
class(elpa_t)     :: \fB elpa\fP  
Returns an instance of the ELPA object
.TP
integer, optional :: \fB error\fP 
A returned error code 
.br

.SS C INTERFACE
#include <elpa/elpa.h>
.br
elpa_t handle;

.br
\fBelpa_t\fP handle =\fB elpa_allocate\fP(\fBint\fP *error);
.sp
With the definitions of the input and output variables:
.TP
elpa_t \fB handle\fP;  // returns an handle to the allocated ELPA object
.TP
int \fB *error\fP;     // a returned error code
.br

.SH DESCRIPTION
Allocate an ELPA object. The function\fB elpa_init\fP(3) must be called once\fI BEFORE\fP\fB elpa_allocate\fP can be called.

.SH SEE ALSO
\fBelpa2_print_kernels\fP(1)\fB elpa_init\fP(3)\fB elpa_set\fP(3)\fB elpa_setup\fP(3)\fB elpa_strerr\fP(3)\fB elpa_eigenvalues\fP(3)\fB elpa_eigenvectors\fP(3)\fB elpa_cholesky\fP(3)\fB elpa_invert_triangular\fP(3)\fB elpa_solve_tridiagonal\fP(3)\fB elpa_hermitian_multiply\fP(3)\fB elpa_uninit\fP(3)\fB elpa_deallocate\fP(3)
