.TH "elpa2_print_kernels" 1 "Wed Aug 9 2023" "ELPA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elpa2_print_kernels \- provides information, which ELPA2 kernels are available on this system.

.SH SYNOPSIS
elpa2_print_kernels

.SH Description
Provides information, which ELPA2 kernels are available on this system.
.br
It is possible to configure ELPA2 such, that different compute intensive 'ELPA2 kernels' can be chosen at runtime. The service binary elpa2_print_kernels will query the library and tell whether ELPA2 has been configured in this way, and if this is the case which kernels can be chosen at runtime. It will furthermore detail whether ELPA has been configured with OpenMP support.

.SH Options
none

.SH Author
A. Marek, MPCDF

.SH Reporting bugs
Report bugs to the ELPA mail elpa-library@mpcdf.mpg.de

.SH SEE ALSO
\fBelpa_init\fP(3)\fB elpa_allocate\fP(3)\fB elpa_set\fP(3)\fB elpa_setup\fP(3)\fB elpa_eigenvalues\fP(3)\fB elpa_eigenvectors\fP(3)\fB elpa_cholesky\fP(3)\fB elpa_invert_triangular\fP(3)\fB elpa_solve_tridiagonal\fP(3)\fB elpa_hermitian_multiply\fP(3)\fB elpa_uninit\fP(3)\fB elpa_deallocate\fP(3)

