#    This file is part of ELPA.
#
#    The ELPA library was originally created by the ELPA consortium, 
#    consisting of the following organizations:
#
#    - Rechenzentrum Garching der Max-Planck-Gesellschaft (RZG), 
#    - Bergische Universität Wuppertal, Lehrstuhl für angewandte
#      Informatik,
#    - Technische Universität München, Lehrstuhl für Informatik mit
#      Schwerpunkt Wissenschaftliches Rechnen , 
#    - Fritz-Haber-Institut, Berlin, Abt. Theorie, 
#    - Max-Plack-Institut für Mathematik in den Naturwissenschaftrn, 
#      Leipzig, Abt. Komplexe Strukutren in Biologie und Kognition, 
#      and  
#    - IBM Deutschland GmbH
#
#
#    More information can be found here:
#    http://elpa.rzg.mpg.de/
#
#    ELPA is free software: you can redistribute it and/or modify
#    it under the terms of the version 3 of the license of the 
#    GNU Lesser General Public License as published by the Free 
#    Software Foundation.
#
#    ELPA is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with ELPA.  If not, see <http://www.gnu.org/licenses/>
#
#    ELPA reflects a substantial effort on the part of the original
#    ELPA consortium, and we ask you to respect the spirit of the
#    license that we chose: i.e., please contribute any changes you
#    may have back to the original ELPA library distribution, and keep
#    any derivatives of ELPA under the same license that we chose for
#    the original distribution, the GNU Lesser General Public License.

# ------------------------------------------------------------------------------
# Please set the variables below according to your system!
# ------------------------------------------------------------------------------

# It is strongly advised, not to use this Makefile, but build ELPA with the 
# configure autotools. If you want to do it anyway, here are some hints


# Settings for Intel Fortran (Linux) with OpenMP and GENERIC_KERNELS:
#
PREPROCESSORFLAGS=-DWITH_OPENMP -DWITH_REAL_GENERIC_KERNEL -DWITH_COMPLEX_GENERIC_KERNEL
F90=mpif90 -O3 -traceback -g -openmp $(PREPROCESSORFLAGS)
F90OPT=$(F90) -xSSE4.2
LIBS = -L/opt/intel/Compiler/11.0/069/mkl/lib/em64t -lmkl_lapack -lmkl -lguide -lpthread \
-lmkl_scalapack_lp64 -lmkl_blacs_intelmpi_lp64
#
all: elpa1_test_real elpa1_test_complex  elpa2_test_real elpa2_test_complex

elpa1_test_real: elpa1_test_real.o elpa1.o
	$(F90) -o $@ elpa1_test_real.o elpa1.o $(LIBS)


elpa1_test_complex: test_complex.o elpa1.o
	$(F90) -o $@ test_complex.o elpa1.o $(LIBS)

elpa2_test_real: elpa2_test_real.o elpa1.o elpa2.o elpa2_kernels_real.o elpa2_kernels_complex.o
	$(F90) -o $@ elpa2_test_real.o elpa1.o elpa2.o elpa2_kernels_real.o elpa2_kernels_complex.o $(LIBS)

elpa2_test_complex: elpa2_test_complex.o elpa1.o elpa2.o elpa2_kernels_real.o elpa2_kernels_complex.o
	$(F90) -o $@ elpa2_test_complex.o elpa1.o elpa2.o elpa2_kernels_real.o  elpa2_kernels_complex.o $(LIBS)

elpa1_test_real.o: elpa1_test_real.F90 elpa1.o
	$(F90) -c $<

elpa1_test_complex.o: elpa1_test_complex.F90 elpa1.o
	$(F90) -c $<

elpa2_test_real.o: elpa2_test_real.F90 elpa1.o elpa2.o
	$(F90) -c $<

elpa2_test_complex2.o: elpa2_test_complex.f90 elpa1.o elpa2.o
	$(F90) -c $<

elpa1.o: ../src/elpa1.F90
	$(F90) -c $<

elpa2.o: ../src/elpa2.F90 elpa1.o
	$(F90) -c ../src/elpa2.F90

elpa2_kernels_real.o: ../src/elpa2_kernels_real.f90
	$(F90OPT) -c ../src/elpa2_kernels_real.f90

elpa2_kernels_complex.o: ../src/elpa2_kernels_complex.f90
	$(F90OPT) -c ../src/elpa2_kernels_complex.f90

clean:
	rm -f *.o *.mod elpa1_test_real elpa1_test_complex elpa2_test_real elpa2_test_complex
