#!/bin/bash

cov_dir=coverage_data
prefix=$cov_dir/coverage_${CI_BUILD_REF}_${CI_BUILD_NAME}
mkdir -p $cov_dir/

for dir in $(find -name "*.gcno" -print0 | xargs -0 -n 1 dirname | sort -u); do
        dir=${dir#./};
        lcov -c -b $PWD -d $dir --to-package $prefix.${dir//\//_}.package;
done
