#!/usr/bin/env python3
"""Parse test_programs.am and generate CMake test definitions.

This script reads ELPA's test_programs.am (which is massive and generated by
``generate_automake_test_programs.py``) and extracts:

  - test program names
  - source file (test/C/test.c, test/Fortran/test.F90, or test/C++/test.cpp)
  - -D compile definitions
  - conditional guards (if WITH_AMD_GPU_VERSION, etc.)
  - default vs extended classification (from check_SCRIPTS suffix)

It outputs a CMake include file that creates test executables and registers
them with CTest.  Extended tests (``_extended.sh`` in autotools) are
registered with the ``DISABLED`` property so they are skipped by default
but can be run with ``ctest --test-dir . -C extended``.

Usage::

    python generate_tests.py test_programs.am config_vars.txt > ElpaTests.cmake

``config_vars.txt`` contains one ``VAR=VALUE`` per line for the
``AM_CONDITIONAL`` variables that are active in the current build (e.g.,
``ENABLE_C_TESTS=1``, ``WITH_NVIDIA_GPU_VERSION=0``, etc.).

The generated test names use the same ``_default`` / ``_extended`` suffix
as autotools so that CI scripts can correlate results across build systems.
"""

import re
import sys
from pathlib import Path


def parse_config_vars(path: str) -> dict[str, bool]:
    """Read config_vars.txt -> {VAR: True/False}."""
    result = {}
    for line in Path(path).read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        k, _, v = line.partition("=")
        result[k.strip()] = v.strip() not in ("0", "no", "false", "")
    return result


def evaluate_condition(
    cond_stack: list[tuple[str, bool]], config: dict[str, bool]
) -> bool:
    """Return True if all conditions in the stack are satisfied."""
    for var, want_true in cond_stack:
        val = config.get(var, False)
        if val != want_true:
            return False
    return True


def parse_test_programs(am_path: str, config: dict[str, bool]) -> list[dict]:
    """Parse test_programs.am and return list of test program dicts.

    Each returned dict has keys: name, source, lang, defines, level.
    *level* is ``"default"`` or ``"extended"`` based on the
    ``check_SCRIPTS`` suffix in the .am file.
    """
    text = Path(am_path).read_text()
    lines = text.splitlines()

    tests = []
    cond_stack: list[tuple[str, bool]] = []
    i = 0
    current_prog = None
    # Map: program name -> "default" | "extended" | "autotune"
    script_level: dict[str, str] = {}

    while i < len(lines):
        line = lines[i].rstrip()
        stripped = line.strip()

        # Track conditionals
        m = re.match(r"^if\s+(\w+)", stripped)
        if m:
            cond_stack.append((m.group(1), True))
            i += 1
            continue

        if stripped == "else":
            if cond_stack:
                var, _ = cond_stack[-1]
                cond_stack[-1] = (var, not cond_stack[-1][1])
            i += 1
            continue

        if stripped.startswith("endif"):
            if cond_stack:
                cond_stack.pop()
            i += 1
            continue

        # Detect check_SCRIPTS lines to classify default vs extended
        m_script = re.match(
            r"check_SCRIPTS\s*\+=\s*(\S+?)_(default|extended|autotune)\.sh",
            stripped,
        )
        if m_script and evaluate_condition(cond_stack, config):
            script_level[m_script.group(1)] = m_script.group(2)
            i += 1
            continue

        # Detect program declaration
        m = re.match(r"(?:noinst_PROGRAMS|bin_PROGRAMS)\s*\+=\s*(\S+)", stripped)
        if m:
            prog_name = m.group(1)
            if evaluate_condition(cond_stack, config):
                current_prog = prog_name
            else:
                # Explicitly clear: this program is skipped by conditionals.
                # Prevents stale current_prog from accepting SOURCES/FLAGS
                # of a same-named program under a different GPU backend.
                current_prog = None
            i += 1
            continue

        # Detect SOURCES
        m = re.match(r"(\w+)_SOURCES\s*=\s*(.+)", stripped)
        if m and current_prog and m.group(1) == current_prog.replace("-", "_"):
            src = m.group(2).strip()
            # Determine language from source file extension
            if src.endswith(".F90"):
                lang = "Fortran"
            elif src.endswith(".cpp"):
                lang = "CXX"
            elif src.endswith(".c"):
                lang = "C"
            else:
                lang = "C"
            # Start collecting this test
            tests.append(
                {
                    "name": current_prog,
                    "source": src,
                    "lang": lang,
                    "defines": [],
                }
            )
            i += 1
            continue

        # Detect FLAGS (CFLAGS, FCFLAGS, CXXFLAGS) with -D defines
        m = re.match(r"(\w+)_(CFLAGS|FCFLAGS|CXXFLAGS)\s*=\s*(.*)", stripped)
        if (
            m
            and current_prog
            and tests
            and tests[-1]["name"] == m.group(1).replace("-", "_")
        ):
            # Collect continuation lines
            flag_text = m.group(3)
            while flag_text.endswith("\\"):
                i += 1
                flag_text = flag_text[:-1] + " " + lines[i].strip()
            # Extract -D flags
            defines = re.findall(r"-D(\S+)", flag_text)
            # Filter out TEST_CASE (string define, we'll set it separately)
            defines = [d for d in defines if not d.startswith("TEST_CASE")]
            tests[-1]["defines"] = defines
            current_prog = None
            i += 1
            continue

        # Also catch LDADD lines (skip, just advance)
        i += 1

    # Assign level to each test from the script_level map
    for t in tests:
        t["level"] = script_level.get(t["name"], "default")

    # Filter out scalapack_all/scalapack_part tests when neither BUILD_FUGAKU
    # nor BUILD_KCOMPUTER is set — the solve_scalapack_{all,part} support
    # functions exist only in the Fugaku/K-computer source paths.
    if not config.get("BUILD_FUGAKU") and not config.get("BUILD_KCOMPUTER"):
        tests = [
            t
            for t in tests
            if "scalapack_all" not in t["name"] and "scalapack_part" not in t["name"]
        ]

    return tests


def emit_cmake(tests: list[dict], output=sys.stdout) -> None:
    """Emit ``elpa_add_test()`` calls for each test program.

    The ``elpa_add_test`` macro (defined in ``test/CMakeLists.txt``) handles
    executable creation, compiler flags, MPI runner, Windows path-length
    workarounds, timeouts, and environment variables.

    Test names include the ``_default`` or ``_extended`` suffix to match
    the autotools wrapper script names.  Extended tests are marked
    ``DISABLED`` so ``ctest`` skips them by default.
    """
    n_default = sum(1 for t in tests if t["level"] == "default")
    n_extended = sum(1 for t in tests if t["level"] == "extended")
    n_autotune = sum(1 for t in tests if t["level"] == "autotune")
    print("# Auto-generated by generate_tests.py — do not edit", file=output)
    print(
        f"# Total: {len(tests)} tests "
        f"({n_default} default, {n_extended} extended, {n_autotune} autotune)",
        file=output,
    )
    print(file=output)

    # Map source files to cmake variables.
    # The cmake variables are set in test/CMakeLists.txt before including this
    # file.  On Windows with ifort, Fortran sources are preprocessed at
    # configure time (via elpa_pp_test_source) to work around #5117.
    src_map = {
        # Main test sources
        "test/Fortran/test.F90": "${_f_src}",
        "test/C/test.c": "${_c_src}",
        "test/C++/test.cpp": "${_cpp_src}",
        # Specialized test sources
        "test/Fortran/test_autotune.F90": "${_f_autotune_src}",
        "test/Fortran/test_invert_triangular.F90": "${_f_invert_triangular_src}",
        "test/Fortran/test_multiple_objs.F90": "${_f_multiple_objs_src}",
        "test/Fortran/test_skewsymmetric.F90": "${_f_skewsymmetric_src}",
        "test/Fortran/test_split_comm.F90": "${_f_split_comm_src}",
        "test/C/test_autotune.c": "${_c_autotune_src}",
        "test/C/test_multiple_objs.c": "${_c_multiple_objs_src}",
        "test/C/test_skewsymmetric.c": "${_c_skewsymmetric_src}",
        "test/C++/test_autotune.cpp": "${_cpp_autotune_src}",
        "test/C++/test_multiple_objs.cpp": "${_cpp_multiple_objs_src}",
        "test/C++/test_skewsymmetric.cpp": "${_cpp_skewsymmetric_src}",
    }

    for t in tests:
        name = t["name"]
        level = t["level"]
        lang = t["lang"]
        src = src_map.get(t["source"], t["source"])
        # CTest name includes the level suffix to match autotools
        ctest_name = f"{name}_{level}"

        # Build the defines list for the elpa_add_test macro
        defs = " ".join(t["defines"]) if t["defines"] else ""

        print(f"elpa_add_test({ctest_name} {src} {lang} {defs})", file=output)

        # Extended and autotune tests are disabled by default (exit 77 in
        # autotools).  Run with ctest -L extended --run-disabled, or re-configure
        # with -DELPA_TEST_EXTENDED=ON for extended and -DELPA_TEST_AUTOTUNE=ON
        # for autotune (both are OFF by default).
        # Tests that iterate over all GPU kernels are extremely long-running
        # (>600s on small GPUs). Give them an extra label for easy exclusion.
        labels = level
        if "all_kernels_gpu" in ctest_name:
            labels = f"{level};gpu_all_kernels"

        if level == "extended":
            print(
                "if(NOT ELPA_TEST_EXTENDED)",
                file=output,
            )
            print(
                f"set_tests_properties({ctest_name} PROPERTIES DISABLED TRUE)",
                file=output,
            )
            print(
                "endif()",
                file=output,
            )
            print(
                f'set_tests_properties({ctest_name} PROPERTIES LABELS "{labels}")',
                file=output,
            )
        elif level == "autotune":
            print(
                "if(NOT ELPA_TEST_AUTOTUNE)",
                file=output,
            )
            print(
                f"set_tests_properties({ctest_name} PROPERTIES DISABLED TRUE)",
                file=output,
            )
            print(
                "endif()",
                file=output,
            )
            print(
                f'set_tests_properties({ctest_name} PROPERTIES LABELS "{level}")',
                file=output,
            )

        print(file=output)


def main():
    if len(sys.argv) < 3:
        print(
            f"Usage: {sys.argv[0]} test_programs.am config_vars.txt",
            file=sys.stderr,
        )
        sys.exit(1)

    config = parse_config_vars(sys.argv[2])
    tests = parse_test_programs(sys.argv[1], config)
    emit_cmake(tests)
    n_default = sum(1 for t in tests if t["level"] == "default")
    n_extended = sum(1 for t in tests if t["level"] == "extended")
    n_autotune = sum(1 for t in tests if t["level"] == "autotune")
    print(
        f"# Generated {len(tests)} test programs "
        f"({n_default} default, {n_extended} extended, {n_autotune} autotune)",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
