#!/bin/bash
echo $PMI_RANK



#if [ $PMI_RANK -lt $PMI_SIZE/2 ] 

export CUDA_PROXY_CLIENT=1

if [ $PMI_RANK -lt 8 ] 
then 
  export CUDA_PROXY_LOG_DIRECTORY=/home-2/pmessmer/projects/elpa/test/log1
  export CUDA_PROXY_PIPE_DIRECTORY=/home-2/pmessmer/projects/elpa/test/pipe1
else
  export CUDA_PROXY_LOG_DIRECTORY=/home-2/pmessmer/projects/elpa/test/log2
  export CUDA_PROXY_PIPE_DIRECTORY=/home-2/pmessmer/projects/elpa/test/pipe2
fi

./test_real2 $*
