#!/bin/bash
echo $PMI_RANK

 export CUDA_PROXY_CLIENT=1

  export CUDA_PROXY_LOG_DIRECTORY=/home-2/pmessmer/projects/elpa/test/log1
  export CUDA_PROXY_PIPE_DIRECTORY=/home-2/pmessmer/projects/elpa/test/pipe1

./test_real2 $*
