#! /bin/bash
echo nodes total
for f in *.txt 
do
    #echo "processing $f... "
    S=`grep " node = " $f | awk '{print $5}'`
    
    TOTAL=`grep "Time (SYSTEM_CLOCK)" $f | awk '{print $7}'`
    if [[ -z "$TOTAL" ]]; then
        continue
    fi
    S+=" "$TOTAL 
    echo $S
done
