#include <elpa/elpa_constants.h>

#define FORTRAN_CONSTANT(name, value) \
        integer(kind=C_INT), parameter :: name = value !ELPA_C_DEFINE

! General constants
 ELPA_CONSTANTS_MAP(FORTRAN_CONSTANT)


! Solver constants
 ELPA_SOLVER_MAP(FORTRAN_CONSTANT)
#undef ELPA_NUMBER_OF_SOLVERS
 FORTRAN_CONSTANT(ELPA_NUMBER_OF_SOLVERS, (0 ELPA_SOLVER_MAP(ELPA_ENUM_SUM)))


! Real kernels
 ELPA_REAL_KERNEL_MAP(FORTRAN_CONSTANT)
#undef ELPA_2STAGE_NUMBER_OF_REAL_KERNELS
 FORTRAN_CONSTANT(ELPA_2STAGE_NUMBER_OF_REAL_KERNELS, & NEWLINE (0 ELPA_REAL_KERNEL_MAP(ELPA_ENUM_SUM) -1))


! Complex kernels
 ELPA_COMPLEX_KERNEL_MAP(FORTRAN_CONSTANT)
#undef ELPA_2STAGE_NUMBER_OF_COMPLEX_KERNELS
 FORTRAN_CONSTANT(ELPA_2STAGE_NUMBER_OF_COMPLEX_KERNELS, & NEWLINE (0 ELPA_COMPLEX_KERNEL_MAP(ELPA_ENUM_SUM) -1))
