find_package(Python3 REQUIRED COMPONENTS Interpreter)

function(_elpa_append_test_value file_path name value)
    file(APPEND "${file_path}" "${name}=${value}\n")
endfunction()

function(_elpa_append_test_bool file_path name condition_name)
    if(${condition_name})
        _elpa_append_test_value("${file_path}" "${name}" "1")
    else()
        _elpa_append_test_value("${file_path}" "${name}" "0")
    endif()
endfunction()

function(elpa_write_test_config_vars output_file)
    set(ELPA_TEST_PROGRAMS
        "auto"
        CACHE STRING
        "Which test programs to build: all, gpu, cpu, auto (default: auto)"
    )
    set_property(
        CACHE ELPA_TEST_PROGRAMS
        PROPERTY STRINGS all gpu cpu auto
    )

    file(WRITE "${output_file}" "# Generated by CMake\n")
    _elpa_append_test_bool("${output_file}" "ENABLE_C_TESTS" ENABLE_C_TESTS)
    _elpa_append_test_bool("${output_file}" "ENABLE_CPP_TESTS" ENABLE_CPP_TESTS)
    _elpa_append_test_bool("${output_file}" "ENABLE_FORTRAN_TESTS" ENABLE_FORTRAN_TESTS)
    _elpa_append_test_bool("${output_file}" "WITH_NVIDIA_GPU_VERSION" WITH_NVIDIA_GPU_VERSION)
    _elpa_append_test_bool("${output_file}" "BUILD_GPU_TESTS" WITH_NVIDIA_GPU_VERSION)
    _elpa_append_test_bool("${output_file}" "WITH_AMD_GPU_VERSION" WITH_AMD_GPU_VERSION)
    _elpa_append_test_value("${output_file}" "WITH_SYCL_GPU_VERSION" "0")
    _elpa_append_test_value("${output_file}" "BUILD_FUGAKU" "0")
    _elpa_append_test_value("${output_file}" "BUILD_KCOMPUTER" "0")
    _elpa_append_test_bool("${output_file}" "WANT_SINGLE_PRECISION_REAL" WANT_SINGLE_PRECISION_REAL)
    _elpa_append_test_bool("${output_file}" "WANT_SINGLE_PRECISION_COMPLEX" WANT_SINGLE_PRECISION_COMPLEX)
    _elpa_append_test_bool("${output_file}" "WITH_MPI" WITH_MPI)
    _elpa_append_test_bool("${output_file}" "WITH_SCALAPACK_TESTS" WITH_MPI)
    _elpa_append_test_bool("${output_file}" "HAVE_SKEWSYMMETRIC" HAVE_SKEWSYMMETRIC)
    _elpa_append_test_bool("${output_file}" "HAVE_REDIRECT" HAVE_REDIRECT)

    if(ELPA_TEST_PROGRAMS STREQUAL "all")
        set(_build_cpu_tests 1)
        set(_build_gpu_tests 1)
        set(_build_extra_tests 1)
    elseif(ELPA_TEST_PROGRAMS STREQUAL "gpu")
        set(_build_cpu_tests 0)
        set(_build_gpu_tests 1)
        set(_build_extra_tests 0)
    elseif(ELPA_TEST_PROGRAMS STREQUAL "cpu")
        set(_build_cpu_tests 1)
        set(_build_gpu_tests 0)
        set(_build_extra_tests 0)
    else()
        if(WITH_NVIDIA_GPU_VERSION OR WITH_AMD_GPU_VERSION)
            set(_build_cpu_tests 0)
            set(_build_gpu_tests 1)
        else()
            set(_build_cpu_tests 1)
            set(_build_gpu_tests 0)
        endif()
        set(_build_extra_tests 0)
    endif()

    if(NOT _build_gpu_tests)
        _elpa_append_test_value("${output_file}" "BUILD_GPU_TESTS" "0")
    endif()
    _elpa_append_test_value("${output_file}" "BUILD_CPU_TESTS" "${_build_cpu_tests}")
    _elpa_append_test_value("${output_file}" "BUILD_EXTRA_TESTS" "${_build_extra_tests}")
    _elpa_append_test_bool("${output_file}" "ENABLE_AUTOTUNING" ENABLE_AUTOTUNING)
    _elpa_append_test_bool(
        "${output_file}"
        "WITH_OPENMP_OFFLOAD_GPU_VERSION"
        WITH_OPENMP_OFFLOAD_GPU_VERSION
    )
endfunction()

function(elpa_generate_tests_include config_file output_file)
    set(_generate_tests_script
        "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/python/generate_tests.py"
    )
    set(_gen_am_script "${CMAKE_SOURCE_DIR}/generate_automake_test_programs.py")
    set(_test_programs_am "${CMAKE_BINARY_DIR}/test_programs.am")
    if(EXISTS "${_gen_am_script}")
        execute_process(
            COMMAND "${Python3_EXECUTABLE}" "${_gen_am_script}"
            OUTPUT_FILE "${_test_programs_am}"
            RESULT_VARIABLE _gen_am_rc
            ERROR_VARIABLE _gen_am_err
        )
        if(NOT _gen_am_rc EQUAL 0)
            message(
                FATAL_ERROR
                "generate_automake_test_programs.py failed (rc=${_gen_am_rc}):\n${_gen_am_err}"
            )
        endif()
    elseif(EXISTS "${CMAKE_SOURCE_DIR}/test_programs.am")
        file(
            COPY "${CMAKE_SOURCE_DIR}/test_programs.am"
            DESTINATION "${CMAKE_BINARY_DIR}"
        )
    else()
        message(
            FATAL_ERROR
            "Cannot generate tests: neither generate_automake_test_programs.py nor test_programs.am found in ${CMAKE_SOURCE_DIR}"
        )
    endif()

    execute_process(
        COMMAND
            "${Python3_EXECUTABLE}" "${_generate_tests_script}"
            "${_test_programs_am}" "${config_file}"
        OUTPUT_FILE "${output_file}"
        RESULT_VARIABLE _gen_tests_rc
        ERROR_VARIABLE _gen_tests_err
    )
    if(NOT _gen_tests_rc EQUAL 0)
        message(
            FATAL_ERROR
            "generate_tests.py failed (rc=${_gen_tests_rc}):\n${_gen_tests_err}"
        )
    endif()
    string(STRIP "${_gen_tests_err}" _gen_tests_status)
    if(_gen_tests_status)
        message(STATUS "ELPA: ${_gen_tests_status}")
    endif()
endfunction()

function(elpa_prepare_fortran_test_source output_var original_source)
    if(NOT (WIN32 AND CMAKE_Fortran_COMPILER_ID MATCHES "Intel"))
        set(${output_var} "${original_source}" PARENT_SCOPE)
        return()
    endif()

    file(READ "${CMAKE_BINARY_DIR}/config-f90.h" _config_f90_content)
    set(_pp_dir "${CMAKE_BINARY_DIR}/ppf")
    file(MAKE_DIRECTORY "${_pp_dir}")

    get_filename_component(_name "${original_source}" NAME)
    get_filename_component(_dir "${original_source}" DIRECTORY)
    set(_output "${_pp_dir}/${_name}")

    file(READ "${original_source}" _content)
    string(
        REPLACE "#include \"config-f90.h\""
        "${_config_f90_content}"
        _content
        "${_content}"
    )

    if(EXISTS "${_dir}/assert.h")
        file(READ "${_dir}/assert.h" _assert_content)
        string(
            REPLACE "#include \"assert.h\""
            "${_assert_content}"
            _content
            "${_content}"
        )
    endif()
    if(EXISTS "${_dir}/../assert.h")
        file(READ "${_dir}/../assert.h" _assert_parent_content)
        string(
            REPLACE "#include \"../assert.h\""
            "${_assert_parent_content}"
            _content
            "${_content}"
        )
    endif()

    file(WRITE "${_output}" "${_content}")
    set(${output_var} "${_output}" PARENT_SCOPE)
endfunction()

function(elpa_add_test name source lang)
    string(REGEX REPLACE "_(default|extended|autotune)$" "" _exe_name "${name}")

    if(WIN32)
        string(MD5 _hash "${_exe_name}")
        string(SUBSTRING "${_hash}" 0 10 _short_hash)
        set(_target "t_${_short_hash}")
    else()
        set(_target "${_exe_name}")
    endif()

    add_executable(${_target} ${source})
    add_dependencies(${_target} elpa_generated_headers)
    target_link_libraries(${_target} PRIVATE elpatest ${ELPA_LIB_TARGET})
    target_include_directories(${_target} PRIVATE ${_test_common_includes})
    set_target_properties(${_target} PROPERTIES OUTPUT_NAME "${_exe_name}")

    # C++ tests that #include the C test via <mpi.h> would otherwise pull in
    # the deprecated MPI C++ class API on OpenMPI ≤ 4.x, requiring
    # libmpi_cxx at link time.  OpenMPI 5.x removed this library entirely.
    # Suppress the C++ bindings via the vendor-specific skip macros so that
    # <mpi.h> provides only the C API, which is all ELPA needs.
    if("${lang}" STREQUAL "CXX")
        target_compile_definitions(${_target}
            PRIVATE OMPI_SKIP_MPICXX MPICH_SKIP_MPICXX _MPICC_H
        )
    endif()

    if(UNIX)
        if(ELPA_CUDA)
            # CUDA link step delegates to the host compiler (gcc/g++), which
            # defaults to PIE on Ubuntu.  Object files from non-GCC compilers
            # (icx, clang) may lack PIE relocations → use -no-pie.
            target_link_options(${_target} PRIVATE $<HOST_LINK:-no-pie>)
        elseif(CMAKE_C_COMPILER_ID STREQUAL "GNU")
            target_link_options(${_target} PRIVATE -no-pie)
        endif()
    endif()

    if("${lang}" STREQUAL "Fortran")
        elpa_apply_fortran_compile_options(${_target})
    endif()
    elpa_apply_cuda_target_options(${_target})

    target_compile_definitions(
        ${_target}
        PRIVATE TEST_CASE="${_exe_name}" ${ARGN}
    )

    if(WITH_MPI)
        set(_mpi_args ${MPIEXEC_NUMPROC_FLAG} ${ELPA_TEST_NPROCS})
        if(
            WIN32
            AND (
                DEFINED ENV{I_MPI_ROOT}
                OR MPI_C_LIBRARY_VERSION_STRING MATCHES "Intel"
            )
        )
            list(PREPEND _mpi_args "-localonly")
        endif()
        add_test(
            NAME ${name}
            COMMAND
                ${MPIEXEC_EXECUTABLE} ${_mpi_args} $<TARGET_FILE:${_target}>
                ${ELPA_TEST_MATRIX_SIZE} ${ELPA_TEST_NEV} ${ELPA_TEST_NBLK}
        )
    else()
        add_test(
            NAME ${name}
            COMMAND
                $<TARGET_FILE:${_target}> ${ELPA_TEST_MATRIX_SIZE}
                ${ELPA_TEST_NEV} ${ELPA_TEST_NBLK}
        )
    endif()

    set_tests_properties(${name} PROPERTIES TIMEOUT 600 SKIP_RETURN_CODE 77)
    if("${_exe_name}" MATCHES "_all_layouts$|_multiple_objs")
        set_tests_properties(${name} PROPERTIES TIMEOUT 1200)
    endif()

    # Precision labels — allows ctest -L single_precision / double_precision
    # and ctest -LE single_precision to exclude single-precision tests.
    set(_labels "")
    if("${name}" MATCHES "_single")
        list(APPEND _labels "single_precision")
    elseif("${name}" MATCHES "_double")
        list(APPEND _labels "double_precision")
    endif()
    # Variant labels
    if("${name}" MATCHES "_extended$")
        list(APPEND _labels "extended")
    elseif("${name}" MATCHES "_autotune$")
        list(APPEND _labels "autotune")
    else()
        list(APPEND _labels "default")
    endif()
    if(_labels)
        set_tests_properties(${name} PROPERTIES LABELS "${_labels}")
    endif()
    if(WIN32)
        set_tests_properties(
            ${name}
            PROPERTIES
                ENVIRONMENT_MODIFICATION
                    "PATH=path_list_prepend:$<TARGET_FILE_DIR:elpa${ELPA_SUFFIX}>"
        )
    endif()
    if(DEFINED ENV{I_MPI_ROOT} OR MPI_C_LIBRARY_VERSION_STRING MATCHES "Intel")
        set_tests_properties(${name} PROPERTIES ENVIRONMENT "I_MPI_FABRICS=shm")
    endif()
endfunction()
