#define ELPA_C_SOLVER_1STAGE 1
#define ELPA_C_SOLVER_2STAGE 2
#define ELPA_C_NUMBER_OF_SOLVERS 2

#ifdef ELPA_H

#define ELPA_SOLVER_1STAGE     ELPA_C_SOLVER_1STAGE
#define ELPA_SOLVER_2STAGE     ELPA_C_SOLVER_2STAGE
#define ELPA_NUMBER_OF_SOLVERS ELPA_C_NUMBER_OF_SOLVERS

#endif
