#define CPU_MANUFACTURER 1
#define GENERIC_INSTR  2
#define BLUEGENE_INSTR 3
#define SSE_INSTR 4
#define AVX_INSTR 5
#define AVX2_INSTR 6
#define AVX512_INSTR 7
#define NVIDIA_INSTR 8
#define AMD_GPU_INSTR 9
#define INTEL_GPU_INSTR 10
#define VSX_INSTR 11
#define ARCH64_INSTR 12
#define SPARC_INSTR 13
#define SVE128_INSTR 14
#define SVE256_INSTR 15
#define SVE512_INSTR 16

#define NUMBER_OF_INSTR 17
